services:
  - type: web
    name: meeteasy
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn meeteasy.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: meeteasy.settings
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
